import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { IStudent } from "@/entities/student";
import { getStudents } from "@/services/students";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [students, setStudents] = useState<IStudent[]>([]);

  useEffect(() => {
    async function fetchData() {
      const students = await getStudents();
      setStudents(students);
    }

    fetchData();

    return () => {
      // cancelling
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>Students</h1>
        </div>
        <div className={styles.description}>
          <ul>
            {students.map((student) => (
              <li key={student.id}>
                {student.id} - {student.name}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
