import StudentForm from "./../components/StudentForm";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FormEvent, useEffect, useState } from "react";
import { IStudent } from "@/entities/student";
import { createStudent, getStudents } from "@/services/students";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [students, setStudents] = useState<IStudent[]>([]);

  async function addStudent(newName: string) {
    const newStudent = await createStudent(newName);
    setStudents([...students, newStudent]);
  }

  async function fetchData() {
    const students = await getStudents();
    setStudents(students);
  }

  useEffect(() => {
    fetchData();

    return () => {
      // cancelling
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>Students</h1>
        </div>
        <div>
          <StudentForm submitForm={addStudent} />
        </div>
        <div className={styles.description}>
          <ul>
            {students.map((student) => (
              <li key={student.id}>
                {student.id} - {student.name}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
